#!/usr/bin/env python3
"""
Fetches Om's Codeforces max rating and solved-problem count and
regenerates cf_data.tex, which resume.tex \\input's.

Handle: om_sharma_ (change HANDLE below if it ever changes).
"""
import json
import sys
import urllib.request

HANDLE = "om_sharma_"
OUT_FILE = "cf_data.tex"


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "resume-auto-updater"})
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read().decode())


def get_max_rating(handle):
    data = fetch(f"https://codeforces.com/api/user.info?handles={handle}")
    if data.get("status") != "OK":
        raise RuntimeError(f"user.info failed: {data.get('comment')}")
    info = data["result"][0]
    # maxRating not present if user never got a rating; fall back to rating
    return info.get("maxRating", info.get("rating", 0))


def get_solved_count(handle):
    data = fetch(f"https://codeforces.com/api/user.status?handle={handle}")
    if data.get("status") != "OK":
        raise RuntimeError(f"user.status failed: {data.get('comment')}")
    solved = set()
    for sub in data["result"]:
        if sub.get("verdict") == "OK":
            prob = sub["problem"]
            key = (prob.get("contestId"), prob.get("index"), prob.get("name"))
            solved.add(key)
    return len(solved)


def main():
    try:
        max_rating = get_max_rating(HANDLE)
        solved = get_solved_count(HANDLE)
    except Exception as e:
        print(f"ERROR fetching Codeforces data: {e}", file=sys.stderr)
        sys.exit(1)

    # Round solved count down to nearest 10 for the "160+" style display
    solved_floor = (solved // 10) * 10

    content = (
        "% AUTO-GENERATED by scripts/update_cf_rating.py — do not edit manually\n"
        f"\\newcommand{{\\cfrating}}{{{max_rating}}}\n"
        f"\\newcommand{{\\cfsolved}}{{{solved_floor}}}\n"
    )

    with open(OUT_FILE, "w") as f:
        f.write(content)

    print(f"Updated {OUT_FILE}: maxRating={max_rating}, solved={solved} (displayed as {solved_floor}+)")


if __name__ == "__main__":
    main()
